new init script and default based on the init skeleton

diff --git a/debian/cfengine3.init b/debian/cfengine3.init
--- a/debian/cfengine3.init
+++ b/debian/cfengine3.init
@@ -1,290 +1,241 @@
-#!/bin/sh
-#
-# Example init.d script with LSB support.
-#
-# Please read this init.d carefully and modify the sections to
-# adjust it to the program you want to run.
-#
-# Copyright (c) 2007 Javier Fernandez-Sanguino <jfs@debian.org>
-#
-# This is free software; you may redistribute it and/or modify
-# it under the terms of the GNU General Public License as
-# published by the Free Software Foundation; either version 2,
-# or (at your option) any later version.
-#
-# This is distributed in the hope that it will be useful, but
-# WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-#
-# You should have received a copy of the GNU General Public License with
-# the Debian operating system, in /usr/share/common-licenses/GPL;  if
-# not, write to the Free Software Foundation, Inc., 59 Temple Place,
-# Suite 330, Boston, MA 02111-1307 USA
-#
+#! /bin/sh
 ### BEGIN INIT INFO
-# Provides:          hello
-# Required-Start:    $network $local_fs
-# Required-Stop:
-# Should-Start:      $named
-# Should-Stop:
+# Provides:          cfengine3
+# Required-Start:    $remote_fs $network $syslog
+# Required-Stop:     $remote_fs $network $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: <Enter a short description of the sortware>
-# Description:       <Enter a long description of the software>
-#                    <...>
-#                    <...>
+# Short-Description: initscript for cfengine3
+# Description:       starts all the daemon needed by cfengine3 if they are
+#                    enabled on /etc/default/cfengine3
 ### END INIT INFO
 
-PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
+# Author: Antonio Radici <antonio@dyne.org>
 
+# Do NOT "set -e"
 
+# PATH should only include /usr/* if it runs after the mountnfs.sh script
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+
+DESC="datacenter management platform"
 NAME=cfengine3
-LOGDIR=/var/log/cfengine3
-DESC=cfengine3
-CFEXECD_DAEMON=/usr/sbin/cf-execd
-CFSERVD_DAEMON=/usr/sbin/cf-serverd
-CFMONITORD_DAEMON=/usr/sbin/cf-monitord
 PIDROOT=/var/run
+SCRIPTNAME=/etc/init.d/$NAME
 
-# Return-status
-RETVAL=0
+CFEXECD_DAEMON=/usr/sbin/cf-execd
+CFSERVERD_DAEMON=/usr/sbin/cf-serverd
+CFMONITORD_DAEMON=/usr/sbin/cf-monitord
 
-test -x $CFEXECD_DAEMON || exit 0
-test -x $CFSERVD_DAEMON || exit 0
-test -x $CFMONITORD_DAEMON || exit 0
+#DAEMON_ARGS="--options args"
+#PIDFILE=/var/run/$NAME.pid
 
-. /lib/lsb/init-functions
+# Exit if the package is not installed
+[ -x "$CFEXECD_DAEMON" ] || exit 0
+[ -x "$CFSERVERD_DAEMON" ] || exit 0
+[ -x "$CFMONITORD_DAEMON" ] || exit 0
 
-# Default options, these can be overriden by the information
-# at /etc/default/$NAME
-DIETIME=10              # Time to wait for the server to die, in seconds
-                        # If this value is set too low you might not
-                        # let some servers to die gracefully and
-                        # 'restart' will not work
-
-
-#FIXME
-#LOGFILE=$LOGDIR/$NAME.log  # Server logfile
-
-# Include defaults if available
+# defaults
 RUN_CFMONITORD=1
 RUN_CFEXECD=1
-RUN_CFSERVD=1
-if [ -f /etc/default/$NAME ] ; then
-    . /etc/default/$NAME
-fi
+RUN_CFSERVERD=1
 
-set -e
+# Read configuration variable file if it is present
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
 
-running_pid() {
-# Check if a given process pid's cmdline matches a given name
-    pid=$1
-    name=$2
-    [ -z "$pid" ] && return 1
-    [ ! -d /proc/$pid ] &&  return 1
-    cmd=`cat /proc/$pid/cmdline | tr "\000" "\n"|head -n 1 |cut -d : -f 1`
-    # Is this the expected server
-    [ "$cmd" != "$name" ] &&  return 1
-    return 0
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
+
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
+. /lib/lsb/init-functions
+
+#
+# Function that starts the daemon/service
+#
+do_start()
+{
+        DAEMON=$1
+        DAEMON_NAME=`basename $DAEMON`
+        PIDFILE="$PIDROOT/$DAEMON_NAME.pid"
+        
+        # get the args
+        [ $DAEMON_NAME = "cf-monitord" ] && DAEMON_ARGS=$CFMONITORD_ARGS
+        [ $DAEMON_NAME = "cf-serverd" ] && DAEMON_ARGS=$CFSERVERD_ARGS
+        [ $DAEMON_NAME = "cf-execd" ] && DAEMON_ARGS=$CFEXECD_ARGS
+
+	# Return
+	#   0 if daemon has been started
+	#   1 if daemon was already running
+	#   2 if daemon could not be started
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
+		|| return 1
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
+		$DAEMON_ARGS \
+		|| return 2
 }
 
-running() {
-    DAEMON=$1
-    DAEMON_NAME=`basename $DAEMON`
-    PIDFILE="$PIDROOT/$DAEMON_NAME.pid"
+#
+# Function that stops the daemon/service
+#
+do_stop()
+{
+        DAEMON=$1
+        DAEMON_NAME=`basename $DAEMON`
+        PIDFILE="$PIDROOT/$DAEMON_NAME.pid"
 
-# Check if the process is running looking at /proc
-# (works for all users)
-
-    # No pidfile, probably no daemon present
-    [ ! -f "$PIDFILE" ] && return 1
-    pid=`cat $PIDFILE`
-    running_pid $pid $DAEMON || return 1
-    return 0
+	# Return
+	#   0 if daemon has been stopped
+	#   1 if daemon was already stopped
+	#   2 if daemon could not be stopped
+	#   other if a failure occurred
+	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $DAEMON_NAME
+	RETVAL="$?"
+	[ "$RETVAL" = 2 ] && return 2
+	# Wait for children to finish too if this is a daemon that forks
+	# and if the daemon is only ever run from this initscript.
+	# If the above conditions are not satisfied then add some other code
+	# that waits for the process to drop all resources that could be
+	# needed by services started subsequently.  A last resort is to
+	# sleep for some time.
+	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
+	[ "$?" = 2 ] && return 2
+	# Many daemons don't delete their pidfiles when they exit.
+	rm -f $PIDFILE
+	return "$RETVAL"
 }
 
-start_server() {
-    DAEMON=$1
-    DAEMON_NAME=`basename $DAEMON`
-    PIDFILE="$PIDROOT/$DAEMON_NAME.pid"
-    
-    start_daemon -p $PIDFILE $DAEMON $DAEMON_OPTS
-    errcode=$?
-    test $errcode = "0" || RETVAL=1
+#
+# Function that sends a SIGHUP to the daemon/service
+#
+do_reload() {
+        DAEMON=$1
+        DAEMON_NAME=`basename $DAEMON`
+        PIDFILE="$PIDROOT/$DAEMON_NAME.pid"
 
-    return $errcode
+	#
+	# If the daemon can reload its configuration without
+	# restarting (for example, when it is sent a SIGHUP),
+	# then implement that here.
+	#
+	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $DAEMON_NAME
+	return 0
 }
 
-stop_server() {
-    DAEMON=$1
-    DAEMON_NAME=`basename $DAEMON`
-    PIDFILE="$PIDROOT/$DAEMON_NAME.pid"
-
-    killproc -p $PIDFILE $DAEMON
-    errcode=$?
-    test $errcode = "0" || RETVAL=1
-
-    return $errcode
-}
-
-reload_server() {
-    DAEMON=$1
-    DAEMON_NAME=`basename $DAEMON`
-    PIDFILE="$PIDROOT/$DAEMON_NAME.pid"
-
-    [ ! -f "$PIDFILE" ] && return 1
-    pid=pidofproc $PIDFILE # This is the daemon's pid
-    # Send a SIGHUP
-    kill -1 $pid
-    errcode=$?
-    test $errcode = "0" || RETVAL=1
-
-    return $errcode
-}
-
-force_stop() {
-    DAEMON=$1
-    DAEMON_NAME=`basename $DAEMON`
-    PIDFILE="$PIDROOT/$DAEMON_NAME.pid"
-
-# Force the process to die killing it manually
-    [ ! -e "$PIDFILE" ] && return
-    if running $DAEMON; then
-        kill -15 $pid
-        # Is it really dead?
-        sleep "$DIETIME"s
-        if running $DAEMON; then
-            kill -9 $pid
-            sleep "$DIETIME"s
-            if running $DAEMON; then
-                echo "Cannot kill $DAEMON_NAME (pid=$pid)!"
-                exit 1
-            fi
+# Function to start the cfengine daemons
+start_cfengine() {
+        RETVAL=0
+        if [ "$RUN_CFMONITORD" = "1" ]; then
+            do_start $CFMONITORD_DAEMON 
+            [ $? = "0" ] || RETVAL=$?
         fi
-    fi
-    rm -f $PIDFILE
+        if [ "$RUN_CFSERVERD" = "1" ]; then
+            do_start $CFSERVERD_DAEMON
+            [ $? = "0" ] || RETVAL=$?
+        fi
+        if [ "$RUN_CFEXECD" = "1" ]; then
+            do_start $CFEXECD_DAEMON
+            [ $? = "0" ] || RETVAL=$?
+        fi
+
+        return $RETVAL
 }
 
+# Function to stop the cfengine daemons
+stop_cfengine() {
+        RETVAL=0
+        if [ "$RUN_CFEXECD" = "1" ]; then
+            do_stop $CFEXECD_DAEMON
+            [ $? = "0" ] || RETVAL=$?
+        fi
+        if [ "$RUN_CFMONITORD" = "1" ]; then
+            do_stop $CFMONITORD_DAEMON 
+            [ $? = "0" ] || RETVAL=$?
+        fi
+        if [ "$RUN_CFSERVERD" = "1" ]; then
+            do_stop $CFSERVERD_DAEMON
+            [ $? = "0" ] || RETVAL=$?
+        fi
+
+        return $RETVAL
+}
+
+# Function to return the status of the cfengine daemons
+status_cfengine() {
+        RETVAL=0
+        if [ "$RUN_CFMONITORD" = "1" ]; then
+                status_of_proc "$CFMONITORD_DAEMON" "cf-monitord"
+                [ $? = 0 ] || RETVAL=1 
+        fi
+        if [ "$RUN_CFSERVERD" = "1" ]; then
+                status_of_proc "$CFSERVERD_DAEMON" "cf-serverd"
+                [ $? = 0 ] || RETVAL=1 
+        fi
+        if [ "$RUN_CFEXECD" = "1" ]; then
+                status_of_proc "$CFEXECD_DAEMON" "cf-execd" 
+                [ $? = 0 ] || RETVAL=1 
+        fi
+
+        return $RETVAL
+}
 
 case "$1" in
   start)
-        log_daemon_msg "Starting $DESC " "$NAME"
-        case "$RUN_CFMONITORD $RUN_CFEXECD $RUN_CFSERVD" in
-            *1*) ;;
-            *) exit 0;;
-        esac
-   
-		if [ ! -f /etc/cfengine3/promises.cf ]; then
-			log_daemon_msg "\nSkipping cfengine3, /etc/cfengine3/promises.cf missing"
-			log_end_msg 0
-			exit 0
-		fi
-
-        RETVAL=0
-        if [ "$RUN_CFMONITORD" = "1" ]; then
-            start_server $CFMONITORD_DAEMON 
-            running $CFMONITORD_DAEMON || RETVAL=1
-        fi
-        if [ "$RUN_CFSERVD" = "1" ]; then
-            start_server $CFSERVD_DAEMON
-            running $CFSERVD_DAEMON || RETVAL=1
-        fi
-        if [ "$RUN_CFEXECD" = "1" ]; then
-            start_server $CFEXECD_DAEMON
-            running $CFEXECD_DAEMON || RETVAL=1
-        fi
-        log_end_msg $RETVAL
-        ;;
+	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+        start_cfengine 
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
+	;;
   stop)
-        RETVAL=0
-        log_daemon_msg "Stopping $DESC" "$NAME"
-        if [ "$RUN_CFMONITORD" = "1" ]; then
-            if running $CFMONITORD_DAEMON; then
-                stop_server $CFMONITORD_DAEMON || RETVAL=1
-            fi
-        fi
-        if [ "$RUN_CFSERVD" = "1" ]; then
-            if running $CFSERVD_DAEMON; then
-                stop_server $CFSERVD_DAEMON || RETVAL=1
-            fi
-        fi
-        if [ "$RUN_CFEXECD" = "1" ]; then
-            if running $CFEXECD_DAEMON; then
-                stop_server $CFEXECD_DAEMON || RETVAL=1
-            fi
-        fi
-        log_end_msg $RETVAL
+	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+        stop_cfengine
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
+	;;
+  status)
+        status_cfengine
+        exit $?
         ;;
-#  force-stop)
-#        # First try to stop gracefully the program
-#        $0 stop
-#        if running; then
-#            # If it's still running try to kill it more forcefully
-#            log_daemon_msg "Stopping (force) $DESC" "$NAME"
-#            errcode=0
-#            force_stop || errcode=$?
-#            log_end_msg $errcode
-#        fi
-#        ;;
-#  restart|force-reload)
-#        log_daemon_msg "Restarting $DESC" "$NAME"
-#        errcode=0
-#        stop_server || errcode=$?
-#        # Wait some sensible amount, some server need this
-#        [ -n "$DIETIME" ] && sleep $DIETIME
-#        start_server || errcode=$?
-#        [ -n "$STARTTIME" ] && sleep $STARTTIME
-#        running || errcode=$?
-#        log_end_msg $errcode
-#        ;;
-#  status)
-#
-#        log_daemon_msg "Checking status of $DESC" "$NAME"
-#        if running ;  then
-#            log_progress_msg "running"
-#            log_end_msg 0
-#        else
-#            log_progress_msg "apparently not running"
-#            log_end_msg 1
-#            exit 1
-#        fi
-#        ;;
-  # Use this if the daemon cannot reload
-  reload)
-        log_warning_msg "Reloading $NAME daemon: not implemented, as the daemon"
-        log_warning_msg "cannot re-read the config file (use restart)."
-        ;;
-  # And this if it cann
-  #reload)
-          #
-          # If the daemon can reload its config files on the fly
-          # for example by sending it SIGHUP, do it here.
-          #
-          # If the daemon responds to changes in its config file
-          # directly anyway, make this a do-nothing entry.
-          #
-          # log_daemon_msg "Reloading $DESC configuration files" "$NAME"
-          # if running ; then
-          #    reload_server
-          #    if ! running ;  then
-          # Process died after we tried to reload
-          #       log_progress_msg "died on reload"
-          #       log_end_msg 1
-          #       exit 1
-          #    fi
-          # else
-          #    log_progress_msg "server is not running"
-          #    log_end_msg 1
-          #    exit 1
-          # fi
-                                                                                    #;;
-
+  #reload|force-reload)
+	#
+	# If do_reload() is not implemented then leave this commented out
+	# and leave 'force-reload' as an alias for 'restart'.
+	#
+	#log_daemon_msg "Reloading $DESC" "$NAME"
+	#do_reload
+	#log_end_msg $?
+	#;;
+  restart|force-reload)
+	#
+	# If the "reload" option is implemented then remove the
+	# 'force-reload' alias
+	#
+	log_daemon_msg "Restarting $DESC" "$NAME"
+	stop_cfengine
+	case "$?" in
+	  0|1)
+                sleep 8; #otherwise the lock db becomes corrupted
+		start_cfengine
+		case "$?" in
+			0) log_end_msg 0 ;;
+			1) log_end_msg 1 ;; # Old process is still running
+			*) log_end_msg 1 ;; # Failed to start
+		esac
+		;;
+	  *)
+	  	# Failed to stop
+		log_end_msg 1
+		;;
+	esac
+	;;
   *)
-        N=/etc/init.d/$NAME
-        echo "Usage: $N {start|stop|force-stop|restart|force-reload|status}" >&2
-        exit 1
-        ;;
+	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
+	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+	exit 3
+	;;
 esac
 
-exit 0
+:
