working init script, added --with-sql=no to the rules

diff --git a/debian/cfengine3.init b/debian/cfengine3.init
--- a/debian/cfengine3.init
+++ b/debian/cfengine3.init
@@ -23,7 +23,7 @@
 # Suite 330, Boston, MA 02111-1307 USA
 #
 ### BEGIN INIT INFO
-# Provides:          cfengine3
+# Provides:          hello
 # Required-Start:    $network $local_fs
 # Required-Stop:
 # Should-Start:      $named
@@ -38,84 +38,42 @@
 
 PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
 
-#DAEMON=/usr/sbin/cfengine3 # Introduce the server's location here
-#NAME=#PACKAGE              # Introduce the short server's name here
-#DESC=#PACKAGE              # Introduce a short description here
 
+NAME=cfengine3
+LOGDIR=/var/log/cfengine3
+DESC=cfengine3
 CFEXECD_DAEMON=/usr/sbin/cf-execd
-CFEXECD_NAME=cf-execd
-CFEXECD_PIDFILE=/var/lib/cfengine3/$CFEXECD_NAME.pid
-
 CFSERVD_DAEMON=/usr/sbin/cf-serverd
-CFSERVD_NAME=cf-serverd
-CFSERVD_PIDFILE=/var/lib/cfengine3/$CFSERVD_NAME.pid
+CFMONITORD_DAEMON=/usr/sbin/cf-monitord
+PIDROOT=/var/lib/cfengine3
 
-LOGDIR=/var/log/cfengine3  # Log directory to use
+# Return-status
+RETVAL=0
 
-test -x $DAEMON || exit 0
+test -x $CFEXECD_DAEMON || exit 0
+test -x $CFSERVD_DAEMON || exit 0
+test -x $CFMONITORD_DAEMON || exit 0
 
 . /lib/lsb/init-functions
 
 # Default options, these can be overriden by the information
 # at /etc/default/$NAME
-DAEMON_OPTS=""          # Additional options given to the server
-#DAEMON_OPTS=""          # Additional options given to the server
-
 DIETIME=10              # Time to wait for the server to die, in seconds
                         # If this value is set too low you might not
                         # let some servers to die gracefully and
                         # 'restart' will not work
 
-#STARTTIME=2             # Time to wait for the server to start, in seconds
-                        # If this value is set each time the server is
-                        # started (on start or restart) the script will
-                        # stall to try to determine if it is running
-                        # If it is not set and the server takes time
-                        # to setup a pid file the log message might
-                        # be a false positive (says it did not start
-                        # when it actually did)
 
-LOGFILE=$LOGDIR/$NAME.log  # Server logfile
-#DAEMONUSER=cfengine3   # Users to run the daemons as. If this value
-                        # is set start-stop-daemon will chuid the server
+#FIXME
+#LOGFILE=$LOGDIR/$NAME.log  # Server logfile
 
 # Include defaults if available
+RUN_CFMONITORD=1
+RUN_CFEXECD=1
+RUN_CFSERVD=1
 if [ -f /etc/default/$NAME ] ; then
     . /etc/default/$NAME
-else 
-    RUN_CFSERVD=1
-    RUN_CFEXECD=1
 fi
-
-# then build the list of daemons we need to start
-DAEMONS_LIST=""
-if [ $RUN_CFEXECD -eq 1 ]; then
-	DAEMONS_LIST="$DAEMONS_LIST $CFEXECD_DAEMON"
-fi
-if [ $RUN_CFSERVD -eq 1 ]; then
-	DAEMONS_LIST="$DAEMONS_LIST $CFSERVD_DAEMON"
-fi
-
-# Use this if you want the user to explicitly set 'RUN' in
-# /etc/default/
-#if [ "x$RUN" != "xyes" ] ; then
-#    log_failure_msg "$NAME disabled, please adjust the configuration to your needs "
-#    log_failure_msg "and then set RUN to 'yes' in /etc/default/$NAME to enable it."
-#    exit 1
-#fi
-
-# Check that the user exists (if we set a user)
-# Does the user exist?
-if [ -n "$DAEMONUSER" ] ; then
-    if getent passwd | grep -q "^$DAEMONUSER:"; then
-        # Obtain the uid and gid
-        DAEMONGID=`getent passwd |grep "^$DAEMONUSER:" | awk -F : '{print $4}'`
-    lse
-        log_failure_msg "The user $DAEMONUSER, required to run $NAME does not exist."
-        exit 1
-    fi
-fi
-
 
 set -e
 
@@ -132,205 +90,166 @@ running_pid() {
 }
 
 running() {
-    RUN_ALL=0 # by default everything is running
+    DAEMON=$1
+    DAEMON_NAME=`basename $DAEMON`
+    PIDFILE="$PIDROOT/$DAEMON_NAME.pid"
 
-    for DAEMON in $DAEMONS_LIST; do
-        DAEMONNAME=$(basename $DAEMON)
-        PIDFILE=/var/lib/cfengine3/$DAEMONNAME.pid
+# Check if the process is running looking at /proc
+# (works for all users)
 
-        # Check if the process is running looking at /proc
-        # (works for all users)
-
-        # No pidfile, probably no daemon present
-        if [ ! -f "$PIDFILE" ]; then
-	    RUN_ALL=1
-		continue
-	fi
-
-        pid=`cat $PIDFILE`
-        running_pid $pid $DAEMON || RUN_ALL=1
-    done
-
-    return $RUN_ALL
+    # No pidfile, probably no daemon present
+    [ ! -f "$PIDFILE" ] && return 1
+    pid=`cat $PIDFILE`
+    running_pid $pid $DAEMON || return 1
+    return 0
 }
 
-start_servers() {
+start_server() {
+    DAEMON=$1
+    DAEMON_NAME=`basename $DAEMON`
+    PIDFILE="$PIDROOT/$DAEMON_NAME.pid"
+    
+    start_daemon -p $PIDFILE $DAEMON $DAEMON_OPTS
+    errcode=$?
+    test $errcode = "0" || RETVAL=1
 
-    for DAEMON in $DAEMONS_LIST; do
-        DAEMONNAME=$(basename $DAEMON)
-        PIDFILE=/var/lib/cfengine3/$DAEMONNAME.pid
-
-        # Start the process using the wrapper
-        if [ -z "$DAEMONUSER" ] ; then
-            start_daemon -p $PIDFILE $DAEMON $DAEMON_OPTS
-            errcode=$?
-        else
-        # if we are using a daemonuser then change the user id
-			echo "DAEMON: $DAEMON PIDFILE: $PIDFILE"	
-            start-stop-daemon --start --quiet --pidfile $PIDFILE \
-                        --chuid $DAEMONUSER \
-                        --exec $DAEMON -- $DAEMON_OPTS
-            errcode=$?
-        fi
-
-        # if it fails we need to stop all the daemons started before
-        if [ $errcode -ne 0 ]; then
-            stop_servers;
-            return $errcode
-        fi
-	sleep 2;
-    done
-
-    return 0;
+    return $errcode
 }
 
-stop_servers() {
-    STOP_ALL=0 # by default we stopped everything
+stop_server() {
+    DAEMON=$1
+    DAEMON_NAME=`basename $DAEMON`
+    PIDFILE="$PIDROOT/$DAEMON_NAME.pid"
 
-    for DAEMON in $DAEMONS_LIST; do
-        DAEMONNAME=$(basename $DAEMON)
-        PIDFILE=/var/lib/cfengine3/$DAEMONNAME.pid
+    killproc -p $PIDFILE $DAEMON
+    errcode=$?
+    test $errcode = "0" || RETVAL=1
 
-# Stop the process using the wrapper
-        if [ -z "$DAEMONUSER" ] ; then
-            killproc -p $PIDFILE $DAEMON
-            errcode=$?
-        else
-# if we are using a daemonuser then look for process that match
-            start-stop-daemon --stop --quiet --pidfile $PIDFILE \
-                        --user $DAEMONUSER \
-                        --exec $DAEMON
-            errcode=$?
-        fi
-
-        # if it fails we still need to stop the other daemons
-        if [ $errcode ]; then
-            STOP_ALL=$errcode
-        fi
-    done
-
-    return $STOP_ALL
+    return $errcode
 }
 
-reload_servers() {
+reload_server() {
+    DAEMON=$1
+    DAEMON_NAME=`basename $DAEMON`
+    PIDFILE="$PIDROOT/$DAEMON_NAME.pid"
 
     [ ! -f "$PIDFILE" ] && return 1
     pid=pidofproc $PIDFILE # This is the daemon's pid
     # Send a SIGHUP
     kill -1 $pid
-    return $?
+    errcode=$?
+    test $errcode = "0" || RETVAL=1
+
+    return $errcode
 }
 
 force_stop() {
-    STOP_ALL=0 # by default we stopped everything
+    DAEMON=$1
+    DAEMON_NAME=`basename $DAEMON`
+    PIDFILE="$PIDROOT/$DAEMON_NAME.pid"
 
-    for DAEMON in $DAEMONS_LIST; do
-        DAEMONNAME=$(basename $DAEMON)
-        PIDFILE=/var/lib/cfengine3/$DAEMONNAME.pid
-
-        # Force the process to die killing it manually
-        [ ! -e "$PIDFILE" ] && return
-        if running ; then
-            kill -15 $pid
-            # Is it really dead?
+# Force the process to die killing it manually
+    [ ! -e "$PIDFILE" ] && return
+    if running $DAEMON; then
+        kill -15 $pid
+        # Is it really dead?
+        sleep "$DIETIME"s
+        if running $DAEMON; then
+            kill -9 $pid
             sleep "$DIETIME"s
-            if running ; then
-                kill -9 $pid
-                sleep "$DIETIME"s
-                pid=`cat $PIDFILE`
-                if -f $PIDFILE && running_pid $pid $DAEMON; then
-                    echo "Cannot kill $NAME (pid=$pid)!"
-                    STOP_ALL=1
-                fi
+            if running $DAEMON; then
+                echo "Cannot kill $DAEMON_NAME (pid=$pid)!"
+                exit 1
             fi
         fi
-        rm -f $PIDFILE
-    done
-
-    if [ $STOP_ALL eq 1 ]; then
-        exit 1;
     fi
-
-    return $STOP_ALL
+    rm -f $PIDFILE
 }
 
 
 case "$1" in
   start)
-        log_daemon_msg "Starting cfengine3"
-        # Check if the daemons are running running first
-        if running ; then
-            log_progress_msg "apparently already running"
-            log_end_msg 0
-            exit 0
-        fi
+        log_daemon_msg "Starting $DESC " "$NAME"
+        case "$RUN_CFMONITORD $RUN_CFEXECD $RUN_CFSERVD" in
+            *1*) ;;
+            *) exit 0;;
+        esac
+   
+		if [ ! -f /var/lib/cfengine3/inputs/promises.cf ]; then
+			log_daemon_msg "\nSkipping cfengine3, /var/lib/cfengine3/inputs/promises.cf missing"
+			log_end_msg 0
+			exit 0
+		fi
 
-        if start_servers ; then
-            # NOTE: Some servers might die some time after they start,
-            # this code will detect this issue if STARTTIME is set
-            # to a reasonable value
-            [ -n "$STARTTIME" ] && sleep $STARTTIME # Wait some time 
-	    ps -efa | grep cf- | grep -v grep
-            if  running ;  then
-                # It's ok, the servers started and are running
-                log_end_msg 0
-            else
-                # It is not running after we did start
-                log_end_msg 1
-            fi
-        else
-            # Either we could not start it
-            log_end_msg 1
+        RETVAL=0
+        if [ "$RUN_CFMONITORD" = "1" ]; then
+            start_server $CFMONITORD_DAEMON 
+            running $CFMONITORD_DAEMON || RETVAL=1
         fi
+        if [ "$RUN_CFEXECD" = "1" ]; then
+            start_server $CFEXECD_DAEMON
+            running $CFEXECD_DAEMON || RETVAL=1
+        fi
+        if [ "$RUN_CFSERVD" = "1" ]; then
+            start_server $CFSERVD_DAEMON
+            running $CFSERVD_DAEMON || RETVAL=1
+        fi
+        log_end_msg $RETVAL
         ;;
   stop)
+        RETVAL=0
         log_daemon_msg "Stopping $DESC" "$NAME"
-        if running ; then
-            # Only stop the server if we see it running
-            errcode=0
-            stop_servers || errcode=$?
-            log_end_msg $errcode
-        else
-            # If it's not running don't do anything
-            log_progress_msg "apparently not running"
-            log_end_msg 0
-            exit 0
+        if [ "$RUN_CFMONITORD" = "1" ]; then
+            if running $CFMONITORD_DAEMON; then
+                stop_server $CFMONITORD_DAEMON || RETVAL=1
+            fi
         fi
-        ;;
-  force-stop)
-        # First try to stop gracefully the program
-        $0 stop
-        if running; then
-            # If it's still running try to kill it more forcefully
-            log_daemon_msg "Stopping (force) $DESC" "$NAME"
-            errcode=0
-            force_stop || errcode=$?
-            log_end_msg $errcode
+        if [ "$RUN_CFEXECD" = "1" ]; then
+            if running $CFEXECD_DAEMON; then
+                stop_server $CFEXECD_DAEMON || RETVAL=1
+            fi
         fi
-        ;;
-  restart|force-reload)
-        log_daemon_msg "Restarting $DESC" "$NAME"
-        errcode=0
-        stop_servers || errcode=$?
-        # Wait some sensible amount, some server need this
-        [ -n "$DIETIME" ] && sleep $DIETIME
-        start_servers || errcode=$?
-        [ -n "$STARTTIME" ] && sleep $STARTTIME
-        running || errcode=$?
-        log_end_msg $errcode
-        ;;
-  status)
-
-        log_daemon_msg "Checking status of $DESC" "$NAME"
-        if running ;  then
-            log_progress_msg "running"
-            log_end_msg 0
-        else
-            log_progress_msg "apparently not running"
-            log_end_msg 1
-            exit 1
+        if [ "$RUN_CFSERVD" = "1" ]; then
+            if running $CFSERVD_DAEMON; then
+                stop_server $CFSERVD_DAEMON || RETVAL=1
+            fi
         fi
+        log_end_msg $RETVAL
         ;;
+#  force-stop)
+#        # First try to stop gracefully the program
+#        $0 stop
+#        if running; then
+#            # If it's still running try to kill it more forcefully
+#            log_daemon_msg "Stopping (force) $DESC" "$NAME"
+#            errcode=0
+#            force_stop || errcode=$?
+#            log_end_msg $errcode
+#        fi
+#        ;;
+#  restart|force-reload)
+#        log_daemon_msg "Restarting $DESC" "$NAME"
+#        errcode=0
+#        stop_server || errcode=$?
+#        # Wait some sensible amount, some server need this
+#        [ -n "$DIETIME" ] && sleep $DIETIME
+#        start_server || errcode=$?
+#        [ -n "$STARTTIME" ] && sleep $STARTTIME
+#        running || errcode=$?
+#        log_end_msg $errcode
+#        ;;
+#  status)
+#
+#        log_daemon_msg "Checking status of $DESC" "$NAME"
+#        if running ;  then
+#            log_progress_msg "running"
+#            log_end_msg 0
+#        else
+#            log_progress_msg "apparently not running"
+#            log_end_msg 1
+#            exit 1
+#        fi
+#        ;;
   # Use this if the daemon cannot reload
   reload)
         log_warning_msg "Reloading $NAME daemon: not implemented, as the daemon"
